language: php

php:
  - 5.6
  - 7.0
  - hhvm

script: phpunit

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
    CODECLIMATE_REPO_TOKEN = 98936fbdc3e3af296fee3ac4478154e745ea987d820d6762462fc7af3c8b5700 ./vendor/bin/test-reporter
